CREATE TABLE ASSUNTO(
	COD INT PRIMARY KEY,
  DESCR VARCHAR(100)
);

CREATE TABLE EDITORA(
	COD INT PRIMARY KEY,
  CNPJ VARCHAR(14) NOT NULL UNIQUE,
  NOME VARCHAR(100) NOT NULL
);

CREATE TABLE AUTOR(
 	COD INT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  PASSAPORTE VARCHAR(30) NOT NULL UNIQUE,
  DT_NASC DATE,
  NACIONALIDADE_COD INT                  
);

CREATE TABLE AUTOR_LIVRO(
    COD INT PRIMARY KEY,
    ISBN VARCHAR(13) NOT NULL UNIQUE,
    TITULO VARCHAR(50) NOT NULL,
    PRECO DOUBLE NOT NULL,
    DT_LANCAMENTO DATE,
    FOREIGN KEY (COD) REFERENCES ASSUNTO(COD),
    FOREIGN KEY (COD) REFERENCES EDITORA(COD)
);
