CREATE TABLE ASSUNTO (
    COD INT PRIMARY KEY,
    DESCR VARCHAR(100)
);

CREATE TABLE EDITORA (
    COD INT PRIMARY KEY,
    CNPJ VARCHAR(14) NOT NULL UNIQUE,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE AUTOR (
    COD INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PASSAPORTE VARCHAR(30) NOT NULL UNIQUE,
    DT_NASC DATE,
    NACIONALIDADE_COD INT
);

CREATE TABLE LIVRO (
    ISBN VARCHAR(13) PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    PRECO DOUBLE NOT NULL,
    DT_LANCAMENTO DATE,
    ASSUNTO_COD INT NOT NULL,
    EDITORA_COD INT NOT NULL,
    FOREIGN KEY (ASSUNTO_COD) REFERENCES ASSUNTO(COD),
    FOREIGN KEY (EDITORA_COD) REFERENCES EDITORA(COD)
);

CREATE TABLE AUTOR_LIVRO (
    AUTOR_COD INT NOT NULL,
    PRIMARY KEY (AUTOR_COD, LIVRO_ISBN),
    FOREIGN KEY (AUTOR_COD) REFERENCES AUTOR(COD),
    FOREIGN KEY (LIVRO_ISBN) REFERENCES LIVRO(ISBN)
);
