CREATE TABLE ASSUNTO (
    CODIGO INT PRIMARY KEY,
    DESCRICAO VARCHAR(100)
);

CREATE TABLE EDITORA (
    CODIGO INT PRIMARY KEY,
    CNPJ VARCHAR(14) NOT NULL UNIQUE,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE NACIONALIDADE (
    CODIGO INT PRIMARY KEY,
    PAIS VARCHAR(50)
);

CREATE TABLE AUTOR (
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PASSAPORTE VARCHAR(30) NOT NULL UNIQUE,
    DATANASCIMENTO DATE,
    NACIONALIDADE_CODIGO INT,
    FOREIGN KEY (NACIONALIDADE_CODIGO) REFERENCES NACIONALIDADE(CODIGO)
);

CREATE TABLE LIVRO (
    CODIGO INT PRIMARY KEY,
    ISBN VARCHAR(13) NOT NULL UNIQUE,
    TITULO VARCHAR(50) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    DATALANCAMENTO DATE,
    ASSUNTO_CODIGO INT NOT NULL,
    EDITORA_CODIGO INT NOT NULL,
    FOREIGN KEY (ASSUNTO_CODIGO) REFERENCES ASSUNTO(CODIGO),
    FOREIGN KEY (EDITORA_CODIGO) REFERENCES EDITORA(CODIGO)
);

CREATE TABLE AUTOR_LIVRO (
    AUTOR_CODIGO INT NOT NULL,
    LIVRO_CODIGO INT NOT NULL,
    PRIMARY KEY (AUTOR_CODIGO, LIVRO_CODIGO),
    FOREIGN KEY (AUTOR_CODIGO) REFERENCES AUTOR(CODIGO),
    FOREIGN KEY (LIVRO_CODIGO) REFERENCES LIVRO(CODIGO)
);
